#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /script_dir/clone ensure=absent force=true
puppet resource file /script_dirr ensure=directory
puppet resource file /script_dir/clone ensure=directory
cd /21049462/script_dir
git clone https://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@github.com/lynnthedev/operate_repo.git
cp -p /21049462/script_dir/index.html /var/www/html
