#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
cd /21049462/script_dir
git clone https://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@github.com/lynnthedev/operate_repo.git
cp -p /21049462/script_dir/index.html /var/www/html
